name: Publish Project

on:
  push:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Push to hub
        env:
          HF_TOKEN: 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
          HF_USERNAME: Happys
          SPACE_NAME: ChatOpen
        run: |
          git clone https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME huggingface
          cd huggingface
          git config user.name Happys
          git config user.email admin@wdsj.one
          echo "Last deploy time: $(date)" > DEPLOY_INFO.txt
          git add DEPLOY_INFO.txt
          git commit -am "auto deploy $(date)"
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main -f
